### PR TITLE
Add GameServer Name length validation

### LINKED ISSUE #541: Labels referencing resources name can be too long
In Kubernetes you can create a resource with a 253 characters long name :

> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

However labels and annotations values are restricted to 63 characters :

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

In Agones we're setting labels value for referencing parent resources, but if a parent resource has a long name this cause errors.

References:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

/cc @victor-prodan

### PR DESCRIPTION
**Pull request by aLekSer**
Fixed return order for other Validate() functions.
Need this change to comply with Label Requirements for Pod.
`generateName` truncates the name to 63 bytes and works as expected - creates valid gs with smaller name.

Closes #541.

### CODE REVIEW

**Comment by markmandel** [comment]
Ack. Sorry @aLekSer - I broke your PR, because I tried to fix a conflict in the code editor.

Can you fix this up, and push again - it's already approved.

**Comment by aLekSer** [comment]
@markmandel  Of cause, I will fix it

**Comment by markmandel** [comment]
Arg! @aLekSer I'm sorry - we conflict again. Can you locally bring this PR back inline with master again please?

**Comment by markmandel** [comment]
I did this manually - since it was being a stickler.. Maybe I shouldn't have? This has been merged though.

**Comment by aLekSer** [comment]
`git rebase master` works much better so. 
Can we close the overall ticket #541 ?

**Pull request closed without merging**
