### PR TITLE
Add explicit local version of agones in go.mod

### LINKED ISSUE #705: gen-api-docs make target is not generating API docs for GameServerAllocation
Faced in #682.
There are bunch of errors while running `make gen-api-docs` from `build` folder, see them below.
Steps to reproduce:
1. git fetch https://github.com/GoogleCloudPlatform/agones.git pull/682/head:pr_682 && git checkout pr_682
1. `make gen-api-docs`

Expected:
`site/content/en/docs/Reference/agones_crd_api_reference.html` got updated.
Actual:
Only blank lines were added.

Current output of the script:
```
$ make gen-api-docs
docker run -e FILE="/go/src/agones.dev/agones/site/content/en/docs/Reference/agones_crd_api_reference.html" -e VERSION=0.10.0 --rm -i -v /Users/alexander.apalikov/go/src/agones.dev/agones/build//.confi$
/gcloud:/root/.config/gcloud -v ~/.kube/:/root/.kube -v ~/.helm:/root/.helm -v /Users/alexander.apalikov/go/src/agones.dev/agones:/go/src/agones.dev/agones -v /Users/alexander.apalikov/go/src/agones.de$
/agones/build//.gocache:/root/.cache/go-build agones-build:de8cde26b9 bash -c "/go/src/agones.dev/agones/site/gen-api-docs.sh"                                                                           
I0415 11:26:13.761044       8 main.go:116] parsing go packages in directory ../../../agones.dev/agones/pkg/apis/                                                                                         
W0415 11:26:28.459739       8 parse.go:239] Ignoring child directory agones.dev/agones/pkg/apis/allocation: unable to import "agones.dev/agones/pkg/apis/allocation": go/build: importGo agones.dev/agone$
/pkg/apis/allocation: exit status 1
go: finding agones.dev/agones/pkg/apis/allocation latest
go: finding agones.dev/agones/pkg/apis latest
go: finding agones.dev/agones/pkg latest
go: finding agones.dev/agones v0.9.0
go: downloading agones.dev/agones v0.9.0
go: extracting agones.dev/agones v0.9.0
can't load package: package agones.dev/agones/pkg/apis/allocation: unknown import path "agones.dev/agones/pkg/apis/allocation": cannot find module providing package agones.dev/agones/pkg/apis/allocation
W0415 11:26:30.195565       8 parse.go:239] Ignoring child directory agones.dev/agones/pkg/apis/allocation/v1alpha1: unable to import "agones.dev/agones/pkg/apis/allocation/v1alpha1": go/build: importGo
 agones.dev/agones/pkg/apis/allocation/v1alpha1: exit status 1
go: finding agones.dev/agones/pkg/apis/allocation/v1alpha1 latest
go: finding agones.dev/agones/pkg/apis/allocation latest
go: finding agones.dev/agones/pkg/apis latest
go: finding agones.dev/agones/pkg latest
can't load package: package agones.dev/agones/pkg/apis/allocation/v1alpha1: unknown import path "agones.dev/agones/pkg/apis/allocation/v1alpha1": cannot find module providing package agones.dev/agones/pkg/apis/allocation/v1alpha1

I0415 11:27:44.167386       8 main.go:202] using package=agones.dev/agones/pkg/apis/stable/v1alpha1
W0415 11:27:44.177908       8 main.go:343] not found external link source for type k8s.io/apimachinery/pkg/util/intstr.IntOrString                                                                       
W0415 11:27:44.178572       8 main.go:343] not found external link source for type k8s.io/apimachinery/pkg/types.UID                                                                                     
W0415 11:27:44.179261       8 main.go:343] not found external link source for type k8s.io/apimachinery/pkg/types.UID                                                                                     
I0415 11:27:44.187743       8 main.go:150] written to /tmp/agones_crd_api_reference.html
{{% feature publishVersion="0.10.0" %}}
```

### PR DESCRIPTION
**Pull request by aLekSer**
Update go.mod which is used by ahmetb/gen-crd-api-reference-docs
utility. Now go does not upload the file from agones.dev/agones repo
instead uses local version of sources.

Closes #705.
For #682 will generate docs properly.

### CODE REVIEW

**Comment by markmandel** [comment]
LGTM, but sanity check - @heartrobotninja you see any issues?

**Comment by heartrobotninja** [comment]
Would it make sense to make the agones import path absolute instead of relative?

**Comment by aLekSer** [comment]
The `gen-crd-api-reference-docs`  utility need relative path, `go mod` command could accept absolute, need to check.

**Comment by aLekSer** [comment]
I need to investigate this, however it looks strange, cause I make change only in local directory:
```
cd /go/src/github.com/ahmetb/gen-crd-api-reference-docs
#Use local version of agones
go mod edit --replace=agones.dev/agones@latest=../../../agones.dev/agones/
go build
```

**Comment by markmandel** [comment]
Oh! I read this wrong. Sorry, entirely my fault. Merging!

**Comment by aLekSer** [comment]
The new go mod versioning system could lead to some misunderstandings at first.

**Pull request merged**
