### PR TITLE
Support private docker registry for controller

### PR DESCRIPTION
**Pull request by Oleksii-Terekhov**
Private docker registry useful for use standalone/internal k8s and for minimize traffic to Google docker registry. 
Due **agones.image.registry** used for controller and sidecar - fleets and gameservers also MUST use secret via PodTemplate
```
apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
...
spec:
...
  template:
    spec:
...
      template:
        spec:
          containers:
          - name: simple-udp
            image: <private registry address>/udp-server:0.3
          imagePullSecrets:
            - name: <docker registry secret name from fleet namespace>
```

### CODE REVIEW

**Comment by Oleksii-Terekhov** [comment]
> Once you've signed (or fixed any issues), please reply here (e.g. `I signed it!`) and we'll verify it.

I signed it!

**Comment by victor-prodan** [comment]
I think this is a subset of #349 , isn't it? :thinking:

**Comment by Oleksii-Terekhov** [comment]
> 
> 
> I think this is a subset of #349 , isn't it? 🤔

o_O yes! Maybe one agones.image.registry for controller and sidecar it's mistake?

**Comment by victor-prodan** [comment]
Well, I don't know about other people but I would prefer to use my own secret yaml named as I want 🤔 
And yes, you need that secret both for controller and sidecar, and it needs to be installed in both namespaces.

**Comment by markmandel** [comment]
I have Cloud priveledge :smile: , so not sure I 100% understand the issues at play here, but can we close this PR now that #349 is merged or is there more to discuss here?

**Comment by victor-prodan** [comment]
@Oleksii-Terekhov you can do the same thing using the Makefile now.
See https://github.com/GoogleCloudPlatform/agones/tree/master/build#running-a-custom-test-environment

**Comment by markmandel** [comment]
Or I would assume, through the documented helm parameters, if they are not using the development tools (which I assume they are not here?)

**Comment by Oleksii-Terekhov** [comment]
OK. I close PR. But please add documentation/examples about **ImagePullSecrets** for controller, sidecar and gameServer (not all end users may able read helm charts or go code or build#running-a-custom-test-environment documentation for realize this possibility)

**Pull request closed without merging**
