### PR TITLE
Adding Kubernetes API server requests metrics

### LINKED ISSUE #546: Grafana: add basic API Server graphs
QPS per resource type/verb:

`sum(rate(apiserver_request_count[5m])) by (resource,verb)`

Latency percentiles for key resource types:

`apiserver_request_latencies_summary{resource=~"gameservers|fleets|pods",verb!~"WATCH|LIST",quantile="0.5"}`

Error rates:

`sum(rate(apiserver_request_count{code!~"2.."}[5m])) by (code)`

Perhaps with a nice drop-down to allow narrowing it down by "resource" for common resource types (fleets, gameservers, pods, etc.)

### PR DESCRIPTION
**Pull request by aLekSer**
New dashboard with dropdown Agones CRD selector.
Contains 4 graphs of `apiserver_request_count` by verb and error code as proposed in the ticket as well as 3 quantiles (0.5, 0.9 and 0.99) for `apiserver_request_latencies_summary`.

Closes #546  .

### CODE REVIEW

**Comment by jkowalski** [comment]
I tried the change, looks promising but we should make it easier to read:

* add legend "as table" and "to the right" and expose "current"
* set label units to requests/sec for throughput and milliseconds or microseconds for latency
* have separate graphs for 50th, 90th, 95th and 99th percentile latencies
* perhaps exclude dimensions with zero value (just add " != 0" to metric)
* perhaps use something like "{{ verb }} {{ resource }} {{ subresource }}"
* perhaps have separate graphs for each subresource (main resource, scale, status, could be a dropdown)

**Comment by aLekSer** [comment]
Hello @jkowalski , 
Thanks for review, will apply your comments.
All this graphs should be on one dashboard and fit in one screen. am I right?
For some reason 0.9 percentile does not show me the plot, I need to understand why.

**Comment by jkowalski** [comment]
Took a look again.

* Can you swap "Main Resource Request Count Per Second" and "Subresource Request Count Per Second"
* The metric in Main Resource Request Count Per Second needs to be `sum(rate(apiserver_request_count{resource=~"[[CustomResourceDefinition]]",verb!~"WATCH|LIST",subresource=""}[5m])) by (resource,verb)` with legend format `{{verb}} {{resource}}`
* Can you change the legend format for `Request Error Rate` to `{{resource}} {{subresource}} {{ code }}`
* TIP: When setting up axes units you can use `Units` dropdown instead of `Label` - this makes the axis able to use smarter labels
* Can you change the title `Request Latency - 0.5 quantile, milliseconds` to simply `Request Latency` and drop the other latency graph? Alternatively we can have 4 hard-coded graphs for all quantiles and remove the quantile dropdown completely. It's actually quite useful to see all quantiles at once even if it requires scrolling (you can make them as wide as the page so they align nicely)

**Comment by aLekSer** [comment]
@jkowalski I have applied all your comments. I only can not make 0.95 metrics show up. When switching to value of 0.9 in query graph become depicted.

**Comment by aLekSer** [comment]
Current look of the graphs (time period by default is 1hour):
screenshot 2019-03-07 at 00 01 46
screenshot 2019-03-07 at 00 02 00

**Comment by aLekSer** [comment]
Checked that we have only 3 quantiles available (0.5, 0.9 and 0.99). So I updated the resulting dashboard file it now contains 7 plots.

**Comment by jkowalski** [comment]
LGTM!

**Pull request merged**
