### PR TITLE
fix setAnnotation for simple-udp to use customized key & value

### PR DESCRIPTION
**Pull request by Yingxin-Jiang**
This is a small fix base on commit https://github.com/GoogleCloudPlatform/agones/commit/ba92be3c4511002d0d10a0e420d44894144b3a86

### CODE REVIEW

**Comment by jkowalski** [comment]
this needs to be built and pushed to container registry, let me do it, then your test will pass.

**Comment by jkowalski** [comment]
`docker push gcr.io/agones-images/udp-server:0.7` complete

can you sync your tree to the latest version and rebase so this commit is minimal?

**Comment by markmandel** [comment]
@jkowalski this LGTM - you got any issues, or can we push this through?

**Comment by Yingxin-Jiang** [comment]
@jkowalski - I didn't see commit related to udp-server:0.7 on https://github.com/GoogleCloudPlatform/agones/commits/master. Do I still need to sync to the latest version? or this can be pulled directly?

**Pull request merged**
