### PR TITLE
Centralise the canonical import paths and more package docs

### PR DESCRIPTION
**Pull request by markmandel**
Put the canonical import path into the main directory, to centralise it, and make sure it's applied across everything.

As a side effect of this work, also added some more package docs.

### CODE REVIEW

**Comment by markmandel** [comment]
.. or maybe it actually makes more sense to drop this into 0.2 and play the safe game. WDYT?

**Comment by enocom** [comment]
@markmandel Yeah. Definitely a nice to have. It's probably just a matter of finding the convention and following it.

**Comment by markmandel** [comment]
SGTM. Moving to 0.2, and this PR can be a thread on how we want to have a convention on this.

**Comment by enocom** [comment]
Take a look at [google-cloud-go](https://github.com/GoogleCloudPlatform/google-cloud-go). The top level `cloud.go` file specifies an import restriction. That same restriction appears nowhere else in subpackages.

If that's any guide, then the single restriction in the `version.go` file is enough.

**Comment by markmandel** [comment]
From going from your above code - maybe there should be an `import.go` (or a `doc.go`) at the top level of this repository (rather than in pkg) - which would cover `pkg`, `cmd` and `sdks/go`.

That would seem to make more sense?

**Comment by enocom** [comment]
Putting the restriction in a `doc.go` file is perfect. Great idea!

**Comment by markmandel** [comment]
Done! PTAL.

**Pull request merged**
