### PR TITLE
Clang-formatted the C++ SDK files.

### PR DESCRIPTION
**Pull request by devjgm**
This addresses part of  #713. This seemed fairly uncontroversial. This PR makes zero semantic changes. It's only a whitespace/formatting change applied by `clang-format -style=Google ...`. 

While I expect no tests to fail from this change, I ran all the tests with `cd build; make test` as the [instructions](https://github.com/GoogleCloudPlatform/agones/tree/master/build#testing-and-building) suggest and they did pass. However, I also introduced an intentional syntax error in the C++ code, and the tests still passed, so I'm not convinced that they're running. Is there some other way that I should/could run the C++ build/test on my local machine before sending a PR?

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/agones/716)

### CODE REVIEW

**Comment by roberthbailey** [comment]
Did you try `cd sdks/cpp; make build` to at verify that the code compiles (for me that tells me I need to install `cmake`...)?

**Comment by devjgm** [comment]
That gives me a different error:

```console
$ cd sdk/cpp
$ make build
...
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Error at CMakeLists.txt:177 (install):
  install TARGETS given target "address_sorting" which does not exist in this
  directory.


CMake Error at CMakeLists.txt:195 (install):
  install TARGETS given target "address_sorting" which does not exist in this
  directory.


-- Configuring incomplete, errors occurred!
See also "/home/jgm/github/devjgm/agones/sdks/cpp/.build/CMakeFiles/CMakeOutput.log".
See also "/home/jgm/github/devjgm/agones/sdks/cpp/.build/CMakeFiles/CMakeError.log".
Makefile:26: recipe for target 'build' failed
make: *** [build] Error 1
```
So, I suspect that the C++ build is currently broken and might not be running in the CI? Or possibly it's just that I don't know how to run it.

Note: the `CMakeLists.txt` file is currently requiring an unnecessarily modern version of cmake (more recent than are contained int apt repos). So I tweaked it[1] to allow cmake version 3.10.0, which should be more than recent enough. As a separate issue, I think the required cmake version should be relaxed.

[1]: My diff was:
```diff
diff --git a/sdks/cpp/CMakeLists.txt b/sdks/cpp/CMakeLists.txt
index 3fe83e63..f3b0d29a 100644
--- a/sdks/cpp/CMakeLists.txt
+++ b/sdks/cpp/CMakeLists.txt
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-cmake_minimum_required (VERSION 3.13.0)
+cmake_minimum_required (VERSION 3.10.0)
 
 project(agones VERSION 0.9.0 HOMEPAGE_URL https://github.com/GoogleCloudPlatform/agones LANGUAGES C CXX)
```

**Comment by dsazonoff** [comment]
@devjgm what is your current build configuration (OS, cmake version, is gRPC pre-installed)? I'll take a look, because on Mac / Win everything is OK.

**Comment by devjgm** [comment]
@dsazonoff 
I'm building on Debian Linux `#1 SMP Debian 4.19.28-2rodete1 (2019-03-18 > 2018)`, cmake 3.12.1, gRPC is not pre-installed.

Also, should I commit this PR even though there appears to be a build failure (though I think it's unrelated).

**Comment by dsazonoff** [comment]
> Also, should I commit this PR even though there appears to be a build failure (though I think it's unrelated).

I think yes, we can merge.
About failed build - probably there are some issues with updating submodules for gRPC repo that is [downloaded by cmake](https://github.com/GoogleCloudPlatform/agones/blob/master/sdks/cpp/cmake/Fetch_gRPC.cmake)? After cmake step you may check .build/grpc folder to be up to date with all gRPC submodules. I'll download a vm with Linux soon.
Another way - use main build scripts with Docker. You may try `SDK_FOLDER=cpp make gen-sdk-grpc` from build folder.

@markmandel please restart tests, I don't understand the reason why they failed. And approve/reject this pull request.

**Comment by markmandel** [comment]
If we are going to enforce Clang formatting, can we put the tooling in the C++ SDK image, and then create a `make format` target (or similar) so we can make this easy for developers who are working on the project?

**Comment by dsazonoff** [comment]
> If we are going to enforce Clang formatting, can we put the tooling in the C++ SDK image, and then create a `make format` target (or similar) so we can make this easy for developers who are working on the project?

I think that it should be as a test during a build, as was originally proposed. Because different developers uses different IDE's, and a lot for them already supports clang formatting. For example, most of time I use CLion, and it supports formatting on the fly, without need of running any build steps.

**Comment by markmandel** [comment]
Are we happy to merge this as is? Happy to approve, but deferring to people with more C++ experience.

**Comment by devjgm** [comment]
fyi, I'm trying to merge this. but every time I try to, the branch is out of date, so I update the branch, then the tests need to re-run, I wait for those, then the branch needs to be updated again :-) Trying again. I'll work one of these times.

**Pull request merged**
