### PR TITLE
Cleanup of grpc go generation code

### PR DESCRIPTION
**Pull request by markmandel**
I'd previously generated this in two places, and looking at it through Godoc, it seemed like a code smell.

Having the generated code in a single place seems like the cleaner option.

### CODE REVIEW

**Comment by markmandel** [comment]
@enocom Curious if you see any issues here?

**Comment by enocom** [comment]
@markmandel Yeah, definitely don't need two generated files. The C++ generated stuff might even be deleted too. 

In theory, the proto file is enough, but since we're providing a Go library, we might as well have the generated code for people consuming things within `pkg`.

**Comment by markmandel** [comment]
Personally, I prefer to keep generated files in the repo - makes clear what is going on (the CRD client is all generated too) - as long as it's header'd appropriately.

Kinda like vendoring dependencies :smile:

**Comment by markmandel** [comment]
Also makes it go-gettable

**Comment by enocom** [comment]
SGTM.

**Pull request merged**
