### PR TITLE
Add validation of the fleet underlying gameserver

### PR DESCRIPTION
**Pull request by aLekSer**
Perform additional validation on a Fleet Gameserver specification .
For #765.

### CODE REVIEW

**Comment by markmandel** [comment]
So this is great for a quick and easy fix (which is nice :+1:) - but makes me wonder if we should move some/all the validation functions down to the *Spec implementations - and then it would be far easier to pass this kind of things down?

Or maybe another way - 

Add a Validate() to `GameServerTemplate` that calls a `GameServerSpec.Validate()`, which is also called by `GameServer.Validate()`

WDYT? Would that be cleaner / easier to maintain?

**Comment by aLekSer** [comment]
Agree with you, need to update this PR.

**Comment by markmandel** [comment]
Should we write a e2e test for this? WDYT?

**Comment by aLekSer** [comment]
Yes, I will prepare E2E test for this change

**Pull request merged**
