### PR TITLE
Add allocator service, docs

### PR DESCRIPTION
**Pull request by slartibaartfast**
This is a service that allocates a game server from a fleet using the Agones API.  It then returns the IP address and port of the allocated game server.  I cleaned up the notes I took while making it, and maybe they might provide some useful documentation for people who are looking to programmatically allocate game servers.

Some things I'm not sure about:
- Is the document create_allocator_service.md more of a Quickstart or a Guide?
- The service in the example uses a container in my public Docker registry...I don't mind, but it might be better off in a repo controlled by this project.
- Step 12 and onward of create_allocator_service might be out of scope.
- The error handling in main.go seem inadequate to me...but maybe it is ok?

Please let me know if this would be useful, and if so, what changes should be made.

### CODE REVIEW

**Comment by slartibaartfast** [comment]
"could not import github.com/gin-gonic/gin (cannot find package \"github.com/gin-gonic/gin"

I guess there isn't any reason why that package would be available to the build system.

**Comment by markmandel** [comment]
Haven't had a deep look, but any reason this can't be done with just the standard lib, rather than with gin?

**Comment by slartibaartfast** [comment]
I can't think of any reason why not off the top of my head.  I'll give it a try.

**Comment by markmandel** [comment]
You didn't have to close this, you could have update it at a later date?

But whatever works for your process! :smile: happy to have the contribution.

**Comment by slartibaartfast** [comment]
I didn't want to clutter up the list of open pull requests.
I'll open it again or send a new one after replacing gin with standard lib packages.

**Pull request closed without merging**
