### PR TITLE
Support Rust SDK

### PR DESCRIPTION
**Pull request by thara**
[Rust](https://www.rust-lang.org/en-US/) is a system programming language that runs fast, has memory safety.
It is good for game server implementation too.

*NOTE*
 The sdk.rs file was generated by the following command on macOS.

```bash
$ cargo install protobuf
$ protoc --rust_out sdks/rust sdk.proto
```

### CODE REVIEW

**Comment by markmandel** [comment]
Sounds great, let us know if you have any questions - happy to answer!

**Comment by thara** [comment]
Sorry, I contained my WIP commits by mistake, so I reverted the commits and rebase to master.

I'm trying to implement SDK by using any one of crates for gRPC.
Please voice your opinions if you have any.

**Comment by markmandel** [comment]
No worries - if you want to keep working locally, but not keep updating the PR, just start a new local branch and continue work from there - you can always rebase/merge/reset it back to the original branch when you are ready :+1:

**Comment by markmandel** [comment]
Given how long this has been open, shall we close this PR for now and reopen/start a new one when we have a more complete Rust SDK implementation?

Just trying to keep things clean 😌👌

**Comment by markmandel** [comment]
@thara since this been inactive for a while, I'm going to close this for now. Please feel free to reopen, or create a new PR when there is more work to show, definitely keen to see it.

**Comment by thara** [comment]
@markmandel I created a new PR to https://github.com/GoogleCloudPlatform/agones/pull/230 .

**Pull request closed without merging**
