### PR TITLE
Add input parameters check on CRD loggers

### LINKED ISSUE #609: Quickstart: Create a Game Server
Found a minor issue- you can't use `kubectl apply` for the initial gameserver, you need `kubectl create` instead or you may get a "resource name may not be empty" error, depending on your kubectl version.

### PR DESCRIPTION
**Pull request by aLekSer**
Check nil pointer parameter to avoid possible panic.
Small test fix also to avoid panic on accessing elements of empty array.

### CODE REVIEW

**Comment by jkowalski** [comment]
there are some unrelated files in this PR, intentional?

**Comment by aLekSer** [comment]
@jkowalski Yes, I added small doc update and test update, because don't want to open two small PRs.

**Comment by aLekSer** [comment]
Well, I decided to split this two logically different changes into two PRs.

**Comment by markmandel** [comment]
Works for me. @jkowalski - any objections? If not, I'll approve + merge.

**Pull request merged**
