### PR TITLE
Allow GameServers to be created in non-default namespace.

### LINKED ISSUE #146: Cannot run GameServer in non-default namespace
I want to start by explaining that this came by my fault by creating the gameserver in the agones-system namespace, but anyway, it should be able to run in any namespace.

It makes the gameserver not being able to get an ip and port where to connect to.
([Step 2 on simple-udp example](https://github.com/GoogleCloudPlatform/agones/blob/master/docs/create_gameserver.md#2-fetch-the-gameserver-status))

Command: `kubectl logs simple-udp-8l26l -c agones-gameserver-sidecar` 
Logs: https://gist.github.com/jmaeso/aa4562bd3ad4e5c91bd1e558e329f8a7

Workaround for this: 
```
After you install Agones - make sure you are back on the default namespace
```

### PR DESCRIPTION
**Pull request by dzlier-gcp**
Closes #146

### CODE REVIEW

**Comment by markmandel** [comment]
Just took this for a spin - built a new image, and installed from `build` tools, but it didn't work for me :(

```json
{
    "error": "error creating Pod for GameServer cpp-simple-zx7m2: pods \"cpp-simple-zx7m2-\" is forbidden: error looking up service account default/agones-sdk: serviceaccount \"agones-sdk\" not found",
    "level": "error",
    "msg": "",
    "obj": "default/cpp-simple-zx7m2",
    "queue": "stable.agones.dev.GameServerController",
    "source": "*gameservers.Controller",
    "time": "2018-03-29T00:32:45Z"
}
```

```json
{
    "level": "error",
    "msg": "error creating Pod for GameServer cpp-simple-zx7m2: pods \"cpp-simple-zx7m2-\" is forbidden: error looking up service account default/agones-sdk: serviceaccount \"agones-sdk\" not found",
    "stack": [
        "agones.dev/agones/pkg/gameservers.(*Controller).syncGameServerCreatingState\n\t/go/src/agones.dev/agones/pkg/gameservers/controller.go:387",
        "agones.dev/agones/pkg/gameservers.(*Controller).syncGameServer\n\t/go/src/agones.dev/agones/pkg/gameservers/controller.go:273",
        "agones.dev/agones/pkg/gameservers.(*Controller).(agones.dev/agones/pkg/gameservers.syncGameServer)-fm\n\t/go/src/agones.dev/agones/pkg/gameservers/controller.go:111",
        "agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).processNextWorkItem\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:97",
        "agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).runWorker\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:73",
        "agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).(agones.dev/agones/pkg/util/workerqueue.runWorker)-fm\n\t/go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:115",
        "agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133",
        "agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134",
        "agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88",
        "runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2361"
    ],
    "time": "2018-03-29T00:32:45Z"
}
```

**Comment by enocom** [comment]
It sounds like there are some possible improvements to how Agones handles namespaces.

For now, I think moving Agones into the non-default namespace is a nice change.

@markmandel Any objections to just merging this?

**Comment by dzlier-gcp** [comment]
The result of merging this would be that all GameServer + Pods would have to be created in the agones-system namespace, so if people are already accustomed to creating them in default, it will break some things.

**Comment by enocom** [comment]
Thinking about upgrade paths is a good point. Since we're in alpha, I think we can still make breaking changes, but we should provide a note in the release notes about it.

**Comment by markmandel** [comment]
So it's not a _hard_ requirement that the Pod be created in the same namespace as the GameServer - but I think logically it makes sense, and it would be confusing to the end user to find them in different places.  If I make a Deployment, my Pods stay in the same Namespace as well.

Forcing people to create GameServers in a specific namespace (other than default) also feels very counter intuitive for any Kubernetes user.

On upgrades - this is alpha -- we can break things, as long as we document them. It's in the root README :smile: 

I feel like there has to be a way to do this - the kubectl user has access to all namespaces, so there has to be a way. May be time to reach out and see who we know who works on RBAC, and get them to review?

**Comment by markmandel** [comment]
...and apparently I'm totally wrong. Chatting with a few people:

> service accounts are namespaced. pods are namespaced. podspecs can only references pods, secrets, service accounts that are local to the namespace.

So this sounds like something we should solve at the #101 (Yaml/Helm packaging) - wherein the user selects which namespaces `GameServers` can be used at install/update time, and all the service accounts that are needed are created at that point. WDYT?

**Comment by markmandel** [comment]
Just to clean up - should we close this PR, and make a note to revisit this in #146 when #101 has the first part of it's work complete (a Helm install that works)

**Comment by enocom** [comment]
Yep. I think that makes sense. @dzlier-gcp What do you think?

**Comment by enocom** [comment]
I'm going to close this in favor of #101.

**Pull request closed without merging**
